dtype_list = [
    ("identifier", "Int64"),
    ("action", "int8"),
    ("reason", "float32"),
    ("open_price", "float32"),
    ("close_price", "float32"),
    ("commission", "float32"),
    ("lot_size", "float32"),
    ("pips", "float32"),
    ("price_sl", "float32"),
    ("price_tp", "float32"),
    ("profit", "float32"),
    ("swap", "float32"),
    ("symbol", "category"),
    ("contract_size", "float32"),
    ("profit_rate", "float32"),
    ("platform", "int8"),
    ("trading_account_login", "Int64"),
]
dtype_dict = dict(dtype_list)
