mode: "A"   # Mode A: Copy allowed between accounts of the same user
# mode: "B"  # Mode B: Copy NOT Allowed between accounts held by the same user

output_dir: "reports/"  # Directory to save reports

# The data source configs for the trades
data_source:
  type: csv  # sqlite
  path: ./data/trades.csv