mode: "A"   # Mode A: Copy allowed between accounts of the same user
# mode: "B"  # Mode B: Copy NOT Allowed between accounts held by the same user
dt_window: 300  # Time window in seconds

output_dir: "reports/"  # Directory to save reports

# The data source configs for the trades
data_sources:
  trades:
    type: csv   # or sqlite
    path: ./data/test_task_trades_short.csv
    parse_dates: ["opened_at", "closed_at"]
  accounts:
    type: csv
    path: ./data/test_task_accounts.csv
    parse_dates: []